# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36dc24b2e0fd88f0f4807683fe828175007fd22ad8af4a0262fc96a4c5036ba366ddbb8d65b7fe27274f6ef325fd68b26edd8971b5eb0bb2d3f5448f094f6fa7

test:
  secret_key_base: 97a246299d3c3d6e800dca5e666be1dd62187674b1de05abf112862c6d89f17542a1cad6226acb8b31cd2013010840db97eba95472c1bd333f70145b935a320a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
